#!/usr/bin/env python2

# to get PIL:  pacman -S python-pillow
# to get Xlib: pacman -S python2-xlib

import os
import random

from PIL import Image
from Xlib import display
from Xlib.ext import xinerama

# Paths of source and target here
imgPath = "/home/stew/Pictures/Wallpapers/"
targetBackground = "/tmp/wallppr.jpg"

# Here we get the screen information
screens = display.Display().xinerama_query_screens().screens

# Find the target width + height of the spliced image
targetwidth = 0
maxheight = 0
for scr in screens:
    targetwidth = targetwidth + scr.width
    if maxheight < scr.height:
        maxheight = scr.height

if (maxheight < 600) or (targetwidth < 1000):
    sys.exit()

# Create our spliced image
imOut = Image.new("RGB", (targetwidth, maxheight), None)

# For each screen, get a random image, resize to fit the screen
# and paste into the spliced image
for scr in screens:
    imagePath = imgPath + random.choice( os.listdir(imgPath) )
    print( imagePath )
    im = Image.open(imagePath)
    im = im.resize((scr.width, scr.height), Image.ANTIALIAS)
    print( "resizing image" )
    imOut.paste( im, (scr.x, scr.y) )
    print( "image merged" )

# Save the image and set it as the background
imOut.save(targetBackground)
print( "Background saved" )



desktopEnv = os.environ['DESKTOP_SESSION']

print( "Desktop enviornment is " + desktopEnv )

if 0: #desktopEnv == "mate":
    print ("Using MATE config")
    os.system('mateconftool-2 -t string -s /desktop/mate/background/picture_filename "file://' + targetBackground + '"')
else:
    print("Using Gnome config")
    os.system('gsettings set org.gnome.desktop.background picture-uri "file://' + targetBackground + '"')
#
# Original bash script:
# pic=(/home/stew/Pictures/Wallpapers/*)
# gsettings set org.gnome.desktop.background picture-uri \
#    "file://${pic[RANDOM % ${#pic[@]}]}"
#

